backend:
  name: gitlab
  repo: mantasandri/quire-iiif-test
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/img"

collections: # A list of collections the CMS should be able to edit
  - name: "page" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Page" # Used in the UI, ie.: "New Post"
    folder: "content"
    slug: "{{year}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: "Title",
          name: "title",
          widget: "string",
          tagname: "h1",
          preview: false,
        }
      - {
          label: "subtitle",
          name: "subtitle",
          widget: "string",
          tagname: "h2",
          preview: false,
        }
      - {label: "weight", name: "weight", widget: "number", preview: false}
      - {label: "type", name: "type", widget: "string", preview: false}
      - {label: "class", name: "class", widget: "string", preview: false}
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mma",
          preview: false,
        }
      - {
          label: "Cover Image",
          name: "image",
          widget: "image",
          required: false,
          tagname: "",
          preview: false,
        }
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
